import type { Lesson } from "@/features/lessons/types";

/**
 * ChessSchool lesson content — constants / data layer (backend-swappable).
 * A future API can return this exact `Lesson[]` shape. Keep this file pure data.
 *
 * School flow per lesson: Learn (info) → Observe (auto-played example) → Try
 * (find the move) → Master. No questionnaire steps. Every FEN and move sequence
 * is verified legal by the curriculum test. `unit` holds the owning class id.
 */

const START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

export const LESSONS: Lesson[] = [
  {
    id: "board-basics",
    unit: "class-pieces",
    title: "The Battlefield",
    subtitle: "Meet the board",
    emoji: "🪵",
    prerequisites: [],
    xp: 20,
    tag: "basics",
    steps: [
      {
        id: "intro",
        kind: "info",
        coach: "Welcome to the academy! Chess is played on 64 squares. White always moves first.",
        fen: START,
      },
      {
        id: "watch-open",
        kind: "observe",
        coach: "Watch a calm opening: both sides claim the centre with their e-pawns.",
        fen: START,
        moves: ["e2:e4", "e7:e5"],
      },
    ],
  },
  {
    id: "pawn-power",
    unit: "class-pieces",
    title: "Pawn Power",
    subtitle: "Move & capture",
    emoji: "♟️",
    prerequisites: ["board-basics"],
    xp: 30,
    tag: "pawns",
    steps: [
      {
        id: "center",
        kind: "move",
        coach: "Pawns move forward. Push your e-pawn two squares to grab the centre!",
        fen: START,
        solution: ["e2:e4"],
        highlight: ["e2"],
        arrows: [{ startSquare: "e2", endSquare: "e4", color: "#34d399" }],
        successText: "Beautiful — the centre is yours!",
        failText: "Try pushing the e-pawn (e2) up two squares to e4.",
        tag: "pawns",
      },
      {
        id: "capture",
        kind: "move",
        coach: "Pawns capture diagonally. Take the enemy pawn!",
        fen: "k7/8/8/3p4/4P3/8/8/7K w - - 0 1",
        solution: ["e4:d5"],
        highlight: ["e4", "d5"],
        successText: "Snap! That's how pawns capture.",
        failText: "Capture diagonally: move your e4 pawn onto d5.",
        tag: "pawns",
      },
    ],
  },
  {
    id: "rook-roads",
    unit: "class-pieces",
    title: "Rook Roads",
    subtitle: "Straight lines",
    emoji: "🏰",
    prerequisites: ["pawn-power"],
    xp: 30,
    tag: "rooks",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "Rooks slide any distance in straight lines — along ranks and files.",
        fen: "k7/8/8/8/3p4/8/8/3R3K w - - 0 1",
        arrows: [{ startSquare: "d1", endSquare: "d4", color: "#5b5bd6" }],
      },
      {
        id: "capture",
        kind: "move",
        coach: "Use your rook's straight-line power to capture the pawn.",
        fen: "k7/8/8/8/3p4/8/8/3R3K w - - 0 1",
        solution: ["d1:d4"],
        highlight: ["d1", "d4"],
        successText: "Direct hit! Rooks love open files.",
        failText: "Slide the rook straight up the d-file onto d4.",
        tag: "rooks",
      },
    ],
  },
  {
    id: "knight-hops",
    unit: "class-pieces",
    title: "Knight Hops",
    subtitle: "The L-shape",
    emoji: "🐴",
    prerequisites: ["rook-roads"],
    xp: 35,
    tag: "knights",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "Knights move in an L: two squares one way, then one across. They leap over pieces!",
        fen: "k7/8/4p3/8/3N4/8/8/7K w - - 0 1",
        arrows: [{ startSquare: "d4", endSquare: "e6", color: "#5b5bd6" }],
      },
      {
        id: "capture",
        kind: "move",
        coach: "Hop your knight in an L to capture the pawn on e6.",
        fen: "k7/8/4p3/8/3N4/8/8/7K w - - 0 1",
        solution: ["d4:e6"],
        highlight: ["d4", "e6"],
        successText: "Nice leap! That's the knight's superpower.",
        failText: "From d4, the L-shaped hop to e6 captures the pawn.",
        tag: "knights",
      },
    ],
  },
  {
    id: "deliver-check",
    unit: "class-checkmate",
    title: "Say Check!",
    subtitle: "Attack the king",
    emoji: "⚡",
    prerequisites: ["knight-hops"],
    xp: 35,
    tag: "checks",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "When you attack the enemy king, that's CHECK. The opponent must respond at once.",
        fen: "k7/8/8/8/8/8/8/3RK3 w - - 0 1",
      },
      {
        id: "give",
        kind: "move",
        coach: "Slide your rook to the 8th rank to put the black king in check!",
        fen: "k7/8/8/8/8/8/8/3RK3 w - - 0 1",
        solution: ["d1:d8"],
        highlight: ["a8"],
        successText: "Check! The king has to react.",
        failText: "Bring the rook to d8 — it attacks along the 8th rank to the king.",
        tag: "checks",
      },
    ],
  },
  {
    id: "mate-in-one",
    unit: "class-checkmate",
    title: "Checkmate!",
    subtitle: "End the game",
    emoji: "👑",
    prerequisites: ["deliver-check"],
    xp: 45,
    tag: "checkmate",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "Checkmate is a check the king cannot escape. It wins the game instantly.",
        fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the rook swing to the back rank — the king is fenced in by its own pawns.",
        fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
        moves: ["a1:a8"],
      },
      {
        id: "mate",
        kind: "move",
        coach: "Now you do it — find the back-rank mate!",
        fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
        solution: ["a1:a8"],
        highlight: ["g8"],
        successText: "Checkmate! The king can't escape its own wall of pawns.",
        failText: "Send the rook all the way to a8 — the king is boxed in.",
        tag: "checkmate",
      },
    ],
  },

  // ── Opening School ──────────────────────────────────────────────────────
  {
    id: "opening-principles",
    unit: "class-principles",
    title: "Opening Rules",
    subtitle: "Centre, develop, castle",
    emoji: "🚀",
    prerequisites: ["pawn-power"],
    xp: 40,
    tag: "openings",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "Three golden rules: control the centre, develop your knights and bishops, and castle your king to safety.",
        fen: START,
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch ideal development: centre pawn, both knights, a bishop, then castling.",
        fen: START,
        moves: ["e2:e4", "e7:e5", "g1:f3", "b8:c6", "f1:c4", "g8:f6", "e1:g1"],
      },
      {
        id: "develop",
        kind: "move",
        coach: "Your turn: develop a knight toward the centre.",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
        solution: ["g1:f3"],
        highlight: ["g1"],
        successText: "Great — knights before bishops, toward the centre.",
        failText: "Develop the kingside knight from g1 to f3.",
        tag: "openings",
      },
    ],
  },
  {
    id: "italian-game",
    unit: "class-openings",
    title: "Italian Game",
    subtitle: "1.e4 e5 2.Nf3 Nc6 3.Bc4",
    emoji: "🇮🇹",
    prerequisites: ["opening-principles"],
    xp: 50,
    tag: "openings",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "The Italian Game is a classical opening: quick development and a bishop aimed at f7, Black's weakest point.",
        fen: START,
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the main line of the Italian Game unfold.",
        fen: START,
        moves: ["e2:e4", "e7:e5", "g1:f3", "b8:c6", "f1:c4"],
      },
      {
        id: "try",
        kind: "move",
        coach: "Play the move that defines the Italian — develop the bishop to eye f7.",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 4 3",
        solution: ["f1:c4"],
        highlight: ["f1", "f7"],
        successText: "That's the Italian Bishop — pointing straight at f7!",
        failText: "Develop the light-squared bishop from f1 to c4.",
        tag: "openings",
      },
    ],
  },
  {
    id: "ruy-lopez",
    unit: "class-openings",
    title: "Ruy Lopez",
    subtitle: "1.e4 e5 2.Nf3 Nc6 3.Bb5",
    emoji: "🇪🇸",
    prerequisites: ["italian-game"],
    xp: 50,
    tag: "openings",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "The Ruy Lopez pressures the c6 knight that defends e5 — one of the most respected openings in chess.",
        fen: START,
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the Spanish bishop pin the defender of e5.",
        fen: START,
        moves: ["e2:e4", "e7:e5", "g1:f3", "b8:c6", "f1:b5"],
      },
      {
        id: "try",
        kind: "move",
        coach: "Play the Ruy Lopez move — attack the knight on c6.",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 4 3",
        solution: ["f1:b5"],
        highlight: ["f1", "c6"],
        successText: "The Spanish bishop — pressure on c6!",
        failText: "Develop the bishop from f1 to b5, attacking the knight.",
        tag: "openings",
      },
    ],
  },
  {
    id: "sicilian-defense",
    unit: "class-openings",
    title: "Sicilian Defense",
    subtitle: "Black fights for the centre",
    emoji: "⚔️",
    prerequisites: ["italian-game"],
    xp: 50,
    tag: "openings",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "Against 1.e4, the Sicilian (1...c5) fights for the centre asymmetrically — the most popular reply at every level.",
        fen: START,
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the Open Sicilian: White trades the d-pawn for active piece play.",
        fen: START,
        moves: ["e2:e4", "c7:c5", "g1:f3", "d7:d6", "d2:d4", "c5:d4", "f3:d4", "g8:f6", "b1:c3"],
      },
      {
        id: "try",
        kind: "move",
        coach: "Facing the Sicilian, develop your knight and prepare d4.",
        fen: "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2",
        solution: ["g1:f3"],
        highlight: ["g1"],
        successText: "Develop and prepare to strike with d4.",
        failText: "Develop the knight from g1 to f3.",
        tag: "openings",
      },
    ],
  },

  // ── Tactics Lab ─────────────────────────────────────────────────────────
  {
    id: "fork-master",
    unit: "class-tactics",
    title: "The Fork",
    subtitle: "Two targets, one move",
    emoji: "🍴",
    prerequisites: ["knight-hops"],
    xp: 50,
    tag: "fork",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "A FORK attacks two pieces at once. Knights are the deadliest forkers.",
        fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the knight leap to c7 — checking the king and hitting the rook.",
        fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
        moves: ["d5:c7"],
      },
      {
        id: "fork",
        kind: "move",
        coach: "Your turn — find the royal fork!",
        fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
        solution: ["d5:c7"],
        successText: "Royal fork! You check the king and win the rook next move.",
        failText: "Look for Nc7 — it checks the king on e8 and hits the rook on a8.",
        tag: "fork",
      },
    ],
  },

  // ── Advanced Tactics ────────────────────────────────────────────────────
  {
    id: "pin-it",
    unit: "class-advtactics",
    title: "The Pin",
    subtitle: "Freeze a defender",
    emoji: "📌",
    prerequisites: ["fork-master"],
    xp: 50,
    tag: "pin",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "A PIN freezes a piece: it can't move because a more valuable piece sits behind it. Pin the knight that guards e5.",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 4 3",
      },
      {
        id: "pin",
        kind: "move",
        coach: "Play the bishop move that pins the c6 knight to the king.",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 4 3",
        solution: ["f1:b5"],
        highlight: ["c6"],
        successText: "Pinned! The knight can't move — it shields its king.",
        failText: "Bishop to b5 pins the knight on c6 to the king on e8.",
        tag: "pin",
      },
    ],
  },
  {
    id: "skewer-it",
    unit: "class-advtactics",
    title: "The Skewer",
    subtitle: "Attack through a king",
    emoji: "🍢",
    prerequisites: ["pin-it"],
    xp: 50,
    tag: "skewer",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "A SKEWER is a pin in reverse: check the king so it must step aside, then capture the piece behind it.",
        fen: "q7/8/8/k7/8/8/8/1R4K1 w - - 0 1",
      },
      {
        id: "skewer",
        kind: "move",
        coach: "Check the king along the a-file — next move you'll win the queen!",
        fen: "q7/8/8/k7/8/8/8/1R4K1 w - - 0 1",
        solution: ["b1:a1"],
        highlight: ["a8"],
        successText: "Skewer! The king must move and the queen falls.",
        failText: "Rook to a1 checks the king; the queen on a8 is then exposed.",
        tag: "skewer",
      },
    ],
  },
  {
    id: "discovered-attack",
    unit: "class-advtactics",
    title: "Discovered Attack",
    subtitle: "Unmask a hidden threat",
    emoji: "🎭",
    prerequisites: ["skewer-it"],
    xp: 55,
    tag: "discovery",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "A DISCOVERED ATTACK: move one piece to unveil an attack from the piece behind it. Your knight hides the rook's aim at the queen.",
        fen: "q5k1/8/8/8/8/N7/8/R5K1 w - - 0 1",
      },
      {
        id: "discover",
        kind: "move",
        coach: "Move the knight off the a-file to discover your rook's attack on the queen.",
        fen: "q5k1/8/8/8/8/N7/8/R5K1 w - - 0 1",
        solution: ["a3:c4", "a3:b5", "a3:c2"],
        highlight: ["a8"],
        successText: "Discovered! The rook now attacks the queen on a8.",
        failText: "Move the knight away from the a-file (e.g. to c4) to unveil the rook.",
        tag: "discovery",
      },
    ],
  },

  // ── Endgame School ──────────────────────────────────────────────────────
  {
    id: "endgame-opposition",
    unit: "class-endgame",
    title: "The Opposition",
    subtitle: "King vs king",
    emoji: "🤴",
    prerequisites: ["mate-in-one"],
    xp: 45,
    tag: "opposition",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "In king endgames, the OPPOSITION wins ground: stand your king directly facing the enemy with one square between — the side NOT to move must give way.",
        fen: "4k3/8/8/8/8/8/8/4K3 w - - 0 1",
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch White march up and seize the opposition on e4 vs e6.",
        fen: "4k3/8/8/8/8/8/8/4K3 w - - 0 1",
        moves: ["e1:e2", "e8:e7", "e2:e3", "e7:e6", "e3:e4"],
      },
    ],
  },
  {
    id: "endgame-promotion",
    unit: "class-endgame",
    title: "Queening a Pawn",
    subtitle: "Promotion",
    emoji: "👑",
    prerequisites: ["endgame-opposition"],
    xp: 45,
    tag: "endgame",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "A pawn that reaches the last rank becomes a queen. Converting an extra pawn is how most endgames are won.",
        fen: "8/4P3/8/8/8/8/8/4K1k1 w - - 0 1",
      },
      {
        id: "promote",
        kind: "move",
        coach: "Push the pawn home — promote to a queen!",
        fen: "8/4P3/8/8/8/8/8/4K1k1 w - - 0 1",
        solution: ["e7:e8"],
        highlight: ["e7", "e8"],
        successText: "A brand-new queen! That's a winning advantage.",
        failText: "Advance the e7 pawn to e8 to promote.",
        tag: "endgame",
      },
    ],
  },
  {
    id: "endgame-qmate",
    unit: "class-endgame",
    title: "King & Queen Mate",
    subtitle: "Finish the game",
    emoji: "♛",
    prerequisites: ["endgame-promotion"],
    xp: 55,
    tag: "checkmate",
    steps: [
      {
        id: "info",
        kind: "info",
        coach: "With a queen and king you can force mate against a lone king. The king does the cornering, the queen delivers.",
        fen: "k7/4Q3/1K6/8/8/8/8/8 w - - 0 1",
      },
      {
        id: "watch",
        kind: "observe",
        coach: "Watch the queen step in, protected by the king — checkmate.",
        fen: "k7/4Q3/1K6/8/8/8/8/8 w - - 0 1",
        moves: ["e7:a7"],
      },
      {
        id: "mate",
        kind: "move",
        coach: "Now you deliver it — the king on b6 guards the queen.",
        fen: "k7/4Q3/1K6/8/8/8/8/8 w - - 0 1",
        solution: ["e7:a7"],
        highlight: ["a8"],
        successText: "Checkmate! King and queen working as a team.",
        failText: "Bring the queen to a7 — your king on b6 protects her.",
        tag: "checkmate",
      },
    ],
  },

  // ── Exams (passing graduates the whole class) ───────────────────────────
  {
    id: "exam-pieces",
    unit: "class-pieces",
    title: "Piece Movement Exam",
    subtitle: "Pass to graduate",
    emoji: "📝",
    prerequisites: [],
    xp: 60,
    tag: "exam",
    exam: true,
    steps: [
      {
        id: "q1",
        kind: "move",
        coach: "Exam Q1 — capture the pawn with your pawn.",
        fen: "k7/8/8/3p4/4P3/8/8/7K w - - 0 1",
        solution: ["e4:d5"],
        successText: "Correct.",
        failText: "Pawns capture diagonally.",
        tag: "exam",
      },
      {
        id: "q2",
        kind: "move",
        coach: "Exam Q2 — capture the pawn with your rook.",
        fen: "k7/8/8/8/3p4/8/8/3R3K w - - 0 1",
        solution: ["d1:d4"],
        successText: "Correct.",
        failText: "Rooks move in straight lines.",
        tag: "exam",
      },
      {
        id: "q3",
        kind: "move",
        coach: "Exam Q3 — capture the pawn with your knight.",
        fen: "k7/8/4p3/8/3N4/8/8/7K w - - 0 1",
        solution: ["d4:e6"],
        successText: "Correct.",
        failText: "Knights move in an L.",
        tag: "exam",
      },
    ],
  },
];

export function getLesson(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}
